# Generated by Django 6.0 on 2025-12-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_console', models.CharField(blank=True, max_length=100, null=True)),
                ('price_on_release', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
