# Generated by Django 6.0 on 2025-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release_console',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price_on_release',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
