# Generated by Django 5.2.9 on 2025-12-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre',
        ),
    ]
