# Generated by Django 5.2.9 on 2026-01-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_name_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_cover',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
